---
title: 'Combined Lessons Learned - QHCI 2021 - Project 2'
author: 'Taylor & Tobias'
date: "19.05.2021"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

## Lessons Learned

In a first step we list all lessons learned that came up during the initial code review phase:

***


* One lesson learned is definitely to add more explanation/text to all code. It is important to clearly explain every step undertaken and to add notes to each step and result. 
* Furthermore, testing assumptions is an important part of the analysis. 

***

* Just include charts that bring value to the workbook. 
* Document what and why you are doing some calculations and visualizations

*** 

* The setup of required packages is well handled and brings good reproducibility

```
# define packages
required_packages <- c("tidyverse", "readr", "ggplot2", "stringr")

# install packages when they are not already included
install.packages(setdiff(required_packages, rownames(installed.packages())))  
```

* The notebook makes good use of the R markdown features with marking text as code or using inline R code

  + Marked as code: ... first of, we define a helper function `read_log_files` that will help read in all the different log files.

  + Inline code: ... our data set contains `ncol(data)` columns (*`colnames(data)`*) and `r nrow(data)` rows for `n_distinct(data$user_id)` different users.
  
  
***


### Top 3 Lessons Learned

We reviewed all these lessons learned and would form the following top three arguments that should be taken into consideration for the combined data analyis:


* Documentation
  + The code snippets itself were missing comments
  + The notebook was missing explanation to the code snippets and their results
  + The explanations were not clear enough or not related to the code snippets
  
* Make good use of `*.rmd` capabilities.
  + Inline R code
  +
  
* Data Wrangling
  +

